name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Generate changelogs
        run: bunx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish
        run: |
          cd packages/tailwindcss-utopia
          bun publish
          cd ../utopia-tailwind-merge
          bun publish
        env:
          BUN_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
